### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by nqfe** [neutrino-hd/settings-pathauf#1]
Hallo Markus.

Wann gibt's mal wieder ein Update?
Deine Senderlisten sind die Besten. (Vor allem sinnvoll sortiert). Dafür nochmal Danke.

**Comment by MarkusVolk** [comment]
Hallo
Die Senderliste ist nicht von mir erstellt worden, sondern vom User Pathauf von coolstream.to Ich hatte ihn damals nur gefragt, ob ich die Liste auf github ablegen darf. Leider wurde die Liste seit Februar nicht mehr aktualisiert. Sobald Pathauf eine aktualisierte Liste veröffentlicht, wird es auch hier ein Update geben
